export const weatherFake = {
  "location": {
      "name": "Belo Horizonte",
      "region": "Minas Gerais",
      "country": "Brazil",
      "lat": -19.92,
      "lon": -43.93,
      "tz_id": "America/Sao_Paulo",
      "localtime_epoch": 1688652758,
      "localtime": "2023-07-06 11:12"
  },
  "current": {
      "last_updated_epoch": 1688652000,
      "last_updated": "2023-07-06 11:00",
      "temp_c": 17.0,
      "temp_f": 62.6,
      "is_day": 1,
      "condition": {
          "text": "Partly cloudy",
          "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
          "code": 1003
      },
      "wind_mph": 5.6,
      "wind_kph": 9.0,
      "wind_degree": 50,
      "wind_dir": "NE",
      "pressure_mb": 1026.0,
      "pressure_in": 30.3,
      "precip_mm": 0.0,
      "precip_in": 0.0,
      "humidity": 63,
      "cloud": 50,
      "feelslike_c": 17.0,
      "feelslike_f": 62.6,
      "vis_km": 10.0,
      "vis_miles": 6.0,
      "uv": 6.0,
      "gust_mph": 4.0,
      "gust_kph": 6.5
  }
}

export const mockFutureWeather = {
    "location": {
        "name": "Belo Horizonte",
        "region": "Minas Gerais",
        "country": "Brazil",
        "lat": -19.92,
        "lon": -43.93,
        "tz_id": "America/Sao_Paulo",
        "localtime_epoch": 1688662866,
        "localtime": "2023-07-06 14:01"
    },
    "current": {
        "last_updated_epoch": 1688662800,
        "last_updated": "2023-07-06 14:00",
        "temp_c": 20.0,
        "temp_f": 68.0,
        "is_day": 1,
        "condition": {
            "text": "Partly cloudy",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
            "code": 1003
        },
        "wind_mph": 8.1,
        "wind_kph": 13.0,
        "wind_degree": 40,
        "wind_dir": "NE",
        "pressure_mb": 1023.0,
        "pressure_in": 30.21,
        "precip_mm": 0.0,
        "precip_in": 0.0,
        "humidity": 40,
        "cloud": 75,
        "feelslike_c": 20.0,
        "feelslike_f": 68.0,
        "vis_km": 10.0,
        "vis_miles": 6.0,
        "uv": 7.0,
        "gust_mph": 3.6,
        "gust_kph": 5.8,
        "air_quality": {
            "co": 243.6999969482422,
            "no2": 3.700000047683716,
            "o3": 77.30000305175781,
            "so2": 4.599999904632568,
            "pm2_5": 3.0,
            "pm10": 6.5,
            "us-epa-index": 1,
            "gb-defra-index": 1
        }
    },
    "forecast": {
        "forecastday": [
            {
                "date": "2023-07-06",
                "date_epoch": 1688601600,
                "day": {
                    "maxtemp_c": 25.1,
                    "maxtemp_f": 77.2,
                    "mintemp_c": 8.9,
                    "mintemp_f": 48.0,
                    "avgtemp_c": 15.7,
                    "avgtemp_f": 60.3,
                    "maxwind_mph": 4.9,
                    "maxwind_kph": 7.9,
                    "totalprecip_mm": 0.0,
                    "totalprecip_in": 0.0,
                    "totalsnow_cm": 0.0,
                    "avgvis_km": 10.0,
                    "avgvis_miles": 6.0,
                    "avghumidity": 59.0,
                    "daily_will_it_rain": 0,
                    "daily_chance_of_rain": 0,
                    "daily_will_it_snow": 0,
                    "daily_chance_of_snow": 0,
                    "condition": {
                        "text": "Sunny",
                        "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                        "code": 1000
                    },
                    "uv": 5.0,
                    "air_quality": {
                        "co": 341.40000244140623,
                        "no2": 12.147999925613403,
                        "o3": 40.592000045776366,
                        "so2": 6.37600004196167,
                        "pm2_5": 5.575999994277954,
                        "pm10": 14.83200008392334,
                        "us-epa-index": 1,
                        "gb-defra-index": 1
                    }
                },
                "astro": {
                    "sunrise": "06:31 AM",
                    "sunset": "05:30 PM",
                    "moonrise": "09:07 PM",
                    "moonset": "09:26 AM",
                    "moon_phase": "Waning Gibbous",
                    "moon_illumination": "91",
                    "is_moon_up": 1,
                    "is_sun_up": 0
                },
                "hour": [
                    {
                        "time_epoch": 1688612400,
                        "time": "2023-07-06 00:00",
                        "temp_c": 10.1,
                        "temp_f": 50.2,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 3.4,
                        "wind_kph": 5.4,
                        "wind_degree": 107,
                        "wind_dir": "ESE",
                        "pressure_mb": 1023.0,
                        "pressure_in": 30.21,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 79,
                        "cloud": 6,
                        "feelslike_c": 9.8,
                        "feelslike_f": 49.6,
                        "windchill_c": 9.8,
                        "windchill_f": 49.6,
                        "heatindex_c": 10.1,
                        "heatindex_f": 50.2,
                        "dewpoint_c": 6.7,
                        "dewpoint_f": 44.1,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 6.9,
                        "gust_kph": 11.2,
                        "uv": 1.0,
                        "air_quality": {
                            "co": 363.79998779296875,
                            "no2": 13.399999618530273,
                            "o3": 29.700000762939453,
                            "so2": 6.099999904632568,
                            "pm2_5": 7.099999904632568,
                            "pm10": 18.600000381469727,
                            "us-epa-index": 1,
                            "gb-defra-index": 1
                        }
                    },
                    {
                        "time_epoch": 1688616000,
                        "time": "2023-07-06 01:00",
                        "temp_c": 9.7,
                        "temp_f": 49.5,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 3.4,
                        "wind_kph": 5.4,
                        "wind_degree": 103,
                        "wind_dir": "ESE",
                        "pressure_mb": 1023.0,
                        "pressure_in": 30.2,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 82,
                        "cloud": 6,
                        "feelslike_c": 9.3,
                        "feelslike_f": 48.7,
                        "windchill_c": 9.3,
                        "windchill_f": 48.7,
                        "heatindex_c": 9.7,
                        "heatindex_f": 49.5,
                        "dewpoint_c": 6.8,
                        "dewpoint_f": 44.2,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 6.9,
                        "gust_kph": 11.2,
                        "uv": 1.0,
                        "air_quality": {
                            "co": 323.79998779296875,
                            "no2": 10.899999618530273,
                            "o3": 31.799999237060547,
                            "so2": 5.5,
                            "pm2_5": 6.199999809265137,
                            "pm10": 17.0,
                            "us-epa-index": 1,
                            "gb-defra-index": 1
                        }
                    },
                    {
                        "time_epoch": 1688619600,
                        "time": "2023-07-06 02:00",
                        "temp_c": 9.4,
                        "temp_f": 48.9,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 3.1,
                        "wind_kph": 5.0,
                        "wind_degree": 113,
                        "wind_dir": "ESE",
                        "pressure_mb": 1023.0,
                        "pressure_in": 30.19,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 84,
                        "cloud": 6,
                        "feelslike_c": 9.1,
                        "feelslike_f": 48.4,
                        "windchill_c": 9.1,
                        "windchill_f": 48.4,
                        "heatindex_c": 9.4,
                        "heatindex_f": 48.9,
                        "dewpoint_c": 6.8,
                        "dewpoint_f": 44.2,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 6.5,
                        "gust_kph": 10.4,
                        "uv": 1.0,
                        "air_quality": {
                            "co": 287.1000061035156,
                            "no2": 8.899999618530273,
                            "o3": 34.29999923706055,
                            "so2": 5.099999904632568,
                            "pm2_5": 4.699999809265137,
                            "pm10": 14.199999809265137,
                            "us-epa-index": 1,
                            "gb-defra-index": 1
                        }
                    },
                    {
                        "time_epoch": 1688623200,
                        "time": "2023-07-06 03:00",
                        "temp_c": 9.2,
                        "temp_f": 48.6,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 3.4,
                        "wind_kph": 5.4,
                        "wind_degree": 111,
                        "wind_dir": "ESE",
                        "pressure_mb": 1023.0,
                        "pressure_in": 30.19,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 85,
                        "cloud": 7,
                        "feelslike_c": 8.7,
                        "feelslike_f": 47.7,
                        "windchill_c": 8.7,
                        "windchill_f": 47.7,
                        "heatindex_c": 9.2,
                        "heatindex_f": 48.6,
                        "dewpoint_c": 6.8,
                        "dewpoint_f": 44.2,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 6.9,
                        "gust_kph": 11.2,
                        "uv": 1.0,
                        "air_quality": {
                            "co": 283.70001220703125,
                            "no2": 8.199999809265137,
                            "o3": 34.70000076293945,
                            "so2": 5.300000190734863,
                            "pm2_5": 4.400000095367432,
                            "pm10": 13.600000381469727,
                            "us-epa-index": 1,
                            "gb-defra-index": 1
                        }
                    },
                    {
                        "time_epoch": 1688626800,
                        "time": "2023-07-06 04:00",
                        "temp_c": 9.0,
                        "temp_f": 48.2,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 3.1,
                        "wind_kph": 5.0,
                        "wind_degree": 116,
                        "wind_dir": "ESE",
                        "pressure_mb": 1023.0,
                        "pressure_in": 30.2,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 86,
                        "cloud": 9,
                        "feelslike_c": 8.6,
                        "feelslike_f": 47.5,
                        "windchill_c": 8.6,
                        "windchill_f": 47.5,
                        "heatindex_c": 9.0,
                        "heatindex_f": 48.2,
                        "dewpoint_c": 6.8,
                        "dewpoint_f": 44.2,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 6.5,
                        "gust_kph": 10.4,
                        "uv": 1.0,
                        "air_quality": {
                            "co": 290.3999938964844,
                            "no2": 8.800000190734863,
                            "o3": 32.5,
                            "so2": 5.5,
                            "pm2_5": 4.699999809265137,
                            "pm10": 13.899999618530273,
                            "us-epa-index": 1,
                            "gb-defra-index": 1
                        }
                    },
                    {
                        "time_epoch": 1688630400,
                        "time": "2023-07-06 05:00",
                        "temp_c": 8.9,
                        "temp_f": 48.0,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 3.1,
                        "wind_kph": 5.0,
                        "wind_degree": 111,
                        "wind_dir": "ESE",
                        "pressure_mb": 1023.0,
                        "pressure_in": 30.22,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 87,
                        "cloud": 12,
                        "feelslike_c": 8.5,
                        "feelslike_f": 47.3,
                        "windchill_c": 8.5,
                        "windchill_f": 47.3,
                        "heatindex_c": 8.9,
                        "heatindex_f": 48.0,
                        "dewpoint_c": 6.8,
                        "dewpoint_f": 44.2,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 6.5,
                        "gust_kph": 10.4,
                        "uv": 1.0,
                        "air_quality": {
                            "co": 307.1000061035156,
                            "no2": 10.300000190734863,
                            "o3": 28.299999237060547,
                            "so2": 6.0,
                            "pm2_5": 5.300000190734863,
                            "pm10": 15.0,
                            "us-epa-index": 1,
                            "gb-defra-index": 1
                        }
                    },
                    {
                        "time_epoch": 1688634000,
                        "time": "2023-07-06 06:00",
                        "temp_c": 9.3,
                        "temp_f": 48.7,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 3.1,
                        "wind_kph": 5.0,
                        "wind_degree": 104,
                        "wind_dir": "ESE",
                        "pressure_mb": 1024.0,
                        "pressure_in": 30.23,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 85,
                        "cloud": 11,
                        "feelslike_c": 8.9,
                        "feelslike_f": 48.0,
                        "windchill_c": 8.9,
                        "windchill_f": 48.0,
                        "heatindex_c": 9.3,
                        "heatindex_f": 48.7,
                        "dewpoint_c": 6.8,
                        "dewpoint_f": 44.2,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 6.5,
                        "gust_kph": 10.4,
                        "uv": 1.0,
                        "air_quality": {
                            "co": 350.5,
                            "no2": 13.5,
                            "o3": 22.0,
                            "so2": 6.400000095367432,
                            "pm2_5": 6.099999904632568,
                            "pm10": 16.600000381469727,
                            "us-epa-index": 1,
                            "gb-defra-index": 1
                        }
                    },
                    {
                        "time_epoch": 1688637600,
                        "time": "2023-07-06 07:00",
                        "temp_c": 13.3,
                        "temp_f": 55.9,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 3.4,
                        "wind_kph": 5.4,
                        "wind_degree": 85,
                        "wind_dir": "E",
                        "pressure_mb": 1024.0,
                        "pressure_in": 30.22,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 70,
                        "cloud": 9,
                        "feelslike_c": 13.4,
                        "feelslike_f": 56.1,
                        "windchill_c": 13.4,
                        "windchill_f": 56.1,
                        "heatindex_c": 13.3,
                        "heatindex_f": 55.9,
                        "dewpoint_c": 7.9,
                        "dewpoint_f": 46.2,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 4.3,
                        "gust_kph": 6.8,
                        "uv": 4.0,
                        "air_quality": {
                            "co": 400.5,
                            "no2": 14.699999809265137,
                            "o3": 19.299999237060547,
                            "so2": 6.800000190734863,
                            "pm2_5": 6.5,
                            "pm10": 17.899999618530273,
                            "us-epa-index": 1,
                            "gb-defra-index": 1
                        }
                    },
                    {
                        "time_epoch": 1688641200,
                        "time": "2023-07-06 08:00",
                        "temp_c": 16.1,
                        "temp_f": 61.0,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 4.5,
                        "wind_kph": 7.2,
                        "wind_degree": 66,
                        "wind_dir": "ENE",
                        "pressure_mb": 1024.0,
                        "pressure_in": 30.22,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 58,
                        "cloud": 10,
                        "feelslike_c": 16.1,
                        "feelslike_f": 61.0,
                        "windchill_c": 16.1,
                        "windchill_f": 61.0,
                        "heatindex_c": 16.1,
                        "heatindex_f": 61.0,
                        "dewpoint_c": 7.9,
                        "dewpoint_f": 46.2,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 5.1,
                        "gust_kph": 8.3,
                        "uv": 5.0,
                        "air_quality": {
                            "co": 387.20001220703125,
                            "no2": 11.800000190734863,
                            "o3": 27.899999618530273,
                            "so2": 7.0,
                            "pm2_5": 6.599999904632568,
                            "pm10": 18.100000381469727,
                            "us-epa-index": 1,
                            "gb-defra-index": 1
                        }
                    },
                    {
                        "time_epoch": 1688644800,
                        "time": "2023-07-06 09:00",
                        "temp_c": 18.3,
                        "temp_f": 64.9,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 4.9,
                        "wind_kph": 7.9,
                        "wind_degree": 40,
                        "wind_dir": "NE",
                        "pressure_mb": 1023.0,
                        "pressure_in": 30.22,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 49,
                        "cloud": 13,
                        "feelslike_c": 18.3,
                        "feelslike_f": 64.9,
                        "windchill_c": 18.3,
                        "windchill_f": 64.9,
                        "heatindex_c": 18.3,
                        "heatindex_f": 64.9,
                        "dewpoint_c": 7.5,
                        "dewpoint_f": 45.5,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 5.6,
                        "gust_kph": 9.0,
                        "uv": 5.0,
                        "air_quality": {
                            "co": 293.70001220703125,
                            "no2": 5.300000190734863,
                            "o3": 50.79999923706055,
                            "so2": 4.599999904632568,
                            "pm2_5": 5.199999809265137,
                            "pm10": 12.100000381469727,
                            "us-epa-index": 1,
                            "gb-defra-index": 1
                        }
                    },
                    {
                        "time_epoch": 1688648400,
                        "time": "2023-07-06 10:00",
                        "temp_c": 20.0,
                        "temp_f": 68.0,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 4.7,
                        "wind_kph": 7.6,
                        "wind_degree": 25,
                        "wind_dir": "NNE",
                        "pressure_mb": 1023.0,
                        "pressure_in": 30.19,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 42,
                        "cloud": 16,
                        "feelslike_c": 20.0,
                        "feelslike_f": 68.0,
                        "windchill_c": 20.0,
                        "windchill_f": 68.0,
                        "heatindex_c": 20.0,
                        "heatindex_f": 68.0,
                        "dewpoint_c": 6.6,
                        "dewpoint_f": 43.9,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 5.4,
                        "gust_kph": 8.6,
                        "uv": 6.0,
                        "air_quality": {
                            "co": 280.3999938964844,
                            "no2": 4.199999809265137,
                            "o3": 61.5,
                            "so2": 4.5,
                            "pm2_5": 4.800000190734863,
                            "pm10": 10.600000381469727,
                            "us-epa-index": 1,
                            "gb-defra-index": 1
                        }
                    },
                    {
                        "time_epoch": 1688652000,
                        "time": "2023-07-06 11:00",
                        "temp_c": 22.3,
                        "temp_f": 72.1,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 4.3,
                        "wind_kph": 6.8,
                        "wind_degree": 14,
                        "wind_dir": "NNE",
                        "pressure_mb": 1021.0,
                        "pressure_in": 30.16,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 36,
                        "cloud": 9,
                        "feelslike_c": 23.9,
                        "feelslike_f": 75.0,
                        "windchill_c": 22.3,
                        "windchill_f": 72.1,
                        "heatindex_c": 23.9,
                        "heatindex_f": 75.0,
                        "dewpoint_c": 6.6,
                        "dewpoint_f": 43.9,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 4.9,
                        "gust_kph": 7.9,
                        "uv": 6.0,
                        "air_quality": {
                            "co": 273.70001220703125,
                            "no2": 3.799999952316284,
                            "o3": 67.19999694824219,
                            "so2": 4.699999809265137,
                            "pm2_5": 4.199999809265137,
                            "pm10": 9.5,
                            "us-epa-index": 1,
                            "gb-defra-index": 1
                        }
                    },
                    {
                        "time_epoch": 1688655600,
                        "time": "2023-07-06 12:00",
                        "temp_c": 23.8,
                        "temp_f": 74.8,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 3.8,
                        "wind_kph": 6.1,
                        "wind_degree": 15,
                        "wind_dir": "NNE",
                        "pressure_mb": 1020.0,
                        "pressure_in": 30.11,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 33,
                        "cloud": 6,
                        "feelslike_c": 24.2,
                        "feelslike_f": 75.6,
                        "windchill_c": 23.8,
                        "windchill_f": 74.8,
                        "heatindex_c": 24.2,
                        "heatindex_f": 75.6,
                        "dewpoint_c": 6.5,
                        "dewpoint_f": 43.7,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 4.5,
                        "gust_kph": 7.2,
                        "uv": 6.0,
                        "air_quality": {
                            "co": 257.0,
                            "no2": 3.299999952316284,
                            "o3": 73.0,
                            "so2": 4.400000095367432,
                            "pm2_5": 3.5999999046325684,
                            "pm10": 7.800000190734863,
                            "us-epa-index": 1,
                            "gb-defra-index": 1
                        }
                    },
                    {
                        "time_epoch": 1688659200,
                        "time": "2023-07-06 13:00",
                        "temp_c": 24.6,
                        "temp_f": 76.3,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 3.8,
                        "wind_kph": 6.1,
                        "wind_degree": 14,
                        "wind_dir": "NNE",
                        "pressure_mb": 1018.0,
                        "pressure_in": 30.07,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 31,
                        "cloud": 5,
                        "feelslike_c": 24.5,
                        "feelslike_f": 76.1,
                        "windchill_c": 24.6,
                        "windchill_f": 76.3,
                        "heatindex_c": 24.5,
                        "heatindex_f": 76.1,
                        "dewpoint_c": 6.3,
                        "dewpoint_f": 43.3,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 4.5,
                        "gust_kph": 7.2,
                        "uv": 6.0,
                        "air_quality": {
                            "co": 250.3000030517578,
                            "no2": 3.4000000953674316,
                            "o3": 77.30000305175781,
                            "so2": 4.400000095367432,
                            "pm2_5": 3.200000047683716,
                            "pm10": 6.800000190734863,
                            "us-epa-index": 1,
                            "gb-defra-index": 1
                        }
                    },
                    {
                        "time_epoch": 1688662800,
                        "time": "2023-07-06 14:00",
                        "temp_c": 25.1,
                        "temp_f": 77.2,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 3.1,
                        "wind_kph": 5.0,
                        "wind_degree": 16,
                        "wind_dir": "NNE",
                        "pressure_mb": 1018.0,
                        "pressure_in": 30.06,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 30,
                        "cloud": 4,
                        "feelslike_c": 24.8,
                        "feelslike_f": 76.6,
                        "windchill_c": 25.1,
                        "windchill_f": 77.2,
                        "heatindex_c": 24.8,
                        "heatindex_f": 76.6,
                        "dewpoint_c": 6.5,
                        "dewpoint_f": 43.7,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 3.6,
                        "gust_kph": 5.8,
                        "uv": 7.0,
                        "air_quality": {
                            "co": 243.6999969482422,
                            "no2": 3.700000047683716,
                            "o3": 77.30000305175781,
                            "so2": 4.599999904632568,
                            "pm2_5": 3.0,
                            "pm10": 6.5,
                            "us-epa-index": 1,
                            "gb-defra-index": 1
                        }
                    },
                    {
                        "time_epoch": 1688666400,
                        "time": "2023-07-06 15:00",
                        "temp_c": 24.6,
                        "temp_f": 76.3,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 3.4,
                        "wind_kph": 5.4,
                        "wind_degree": 23,
                        "wind_dir": "NNE",
                        "pressure_mb": 1018.0,
                        "pressure_in": 30.05,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 31,
                        "cloud": 4,
                        "feelslike_c": 24.6,
                        "feelslike_f": 76.3,
                        "windchill_c": 24.6,
                        "windchill_f": 76.3,
                        "heatindex_c": 24.6,
                        "heatindex_f": 76.3,
                        "dewpoint_c": 6.5,
                        "dewpoint_f": 43.7,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 3.8,
                        "gust_kph": 6.1,
                        "uv": 6.0,
                        "air_quality": {
                            "co": 320.3999938964844,
                            "no2": 10.600000381469727,
                            "o3": 65.80000305175781,
                            "so2": 7.300000190734863,
                            "pm2_5": 4.400000095367432,
                            "pm10": 9.5,
                            "us-epa-index": 1,
                            "gb-defra-index": 1
                        }
                    },
                    {
                        "time_epoch": 1688670000,
                        "time": "2023-07-06 16:00",
                        "temp_c": 21.9,
                        "temp_f": 71.4,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 2.5,
                        "wind_kph": 4.0,
                        "wind_degree": 48,
                        "wind_dir": "NE",
                        "pressure_mb": 1018.0,
                        "pressure_in": 30.06,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 39,
                        "cloud": 4,
                        "feelslike_c": 21.9,
                        "feelslike_f": 71.4,
                        "windchill_c": 21.9,
                        "windchill_f": 71.4,
                        "heatindex_c": 23.9,
                        "heatindex_f": 75.0,
                        "dewpoint_c": 7.5,
                        "dewpoint_f": 45.5,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 2.9,
                        "gust_kph": 4.7,
                        "uv": 6.0,
                        "air_quality": {
                            "co": 440.6000061035156,
                            "no2": 23.0,
                            "o3": 43.599998474121094,
                            "so2": 9.199999809265137,
                            "pm2_5": 6.099999904632568,
                            "pm10": 14.100000381469727,
                            "us-epa-index": 1,
                            "gb-defra-index": 1
                        }
                    },
                    {
                        "time_epoch": 1688673600,
                        "time": "2023-07-06 17:00",
                        "temp_c": 18.8,
                        "temp_f": 65.8,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 2.9,
                        "wind_kph": 4.7,
                        "wind_degree": 84,
                        "wind_dir": "E",
                        "pressure_mb": 1019.0,
                        "pressure_in": 30.09,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 46,
                        "cloud": 4,
                        "feelslike_c": 18.8,
                        "feelslike_f": 65.8,
                        "windchill_c": 18.8,
                        "windchill_f": 65.8,
                        "heatindex_c": 18.8,
                        "heatindex_f": 65.8,
                        "dewpoint_c": 7.0,
                        "dewpoint_f": 44.6,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 4.7,
                        "gust_kph": 7.6,
                        "uv": 5.0,
                        "air_quality": {
                            "co": 527.4000244140625,
                            "no2": 35.599998474121094,
                            "o3": 18.200000762939453,
                            "so2": 9.800000190734863,
                            "pm2_5": 7.099999904632568,
                            "pm10": 17.5,
                            "us-epa-index": 1,
                            "gb-defra-index": 1
                        }
                    },
                    {
                        "time_epoch": 1688677200,
                        "time": "2023-07-06 18:00",
                        "temp_c": 17.6,
                        "temp_f": 63.7,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 3.1,
                        "wind_kph": 5.0,
                        "wind_degree": 98,
                        "wind_dir": "E",
                        "pressure_mb": 1020.0,
                        "pressure_in": 30.11,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 51,
                        "cloud": 4,
                        "feelslike_c": 17.6,
                        "feelslike_f": 63.7,
                        "windchill_c": 17.6,
                        "windchill_f": 63.7,
                        "heatindex_c": 17.6,
                        "heatindex_f": 63.7,
                        "dewpoint_c": 7.3,
                        "dewpoint_f": 45.1,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 5.1,
                        "gust_kph": 8.3,
                        "uv": 1.0,
                        "air_quality": {
                            "co": 567.4000244140625,
                            "no2": 36.70000076293945,
                            "o3": 7.699999809265137,
                            "so2": 9.800000190734863,
                            "pm2_5": 8.300000190734863,
                            "pm10": 21.200000762939453,
                            "us-epa-index": 1,
                            "gb-defra-index": 1
                        }
                    },
                    {
                        "time_epoch": 1688680800,
                        "time": "2023-07-06 19:00",
                        "temp_c": 16.6,
                        "temp_f": 61.9,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 3.4,
                        "wind_kph": 5.4,
                        "wind_degree": 99,
                        "wind_dir": "E",
                        "pressure_mb": 1020.0,
                        "pressure_in": 30.13,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 56,
                        "cloud": 4,
                        "feelslike_c": 16.6,
                        "feelslike_f": 61.9,
                        "windchill_c": 16.6,
                        "windchill_f": 61.9,
                        "heatindex_c": 16.6,
                        "heatindex_f": 61.9,
                        "dewpoint_c": 7.8,
                        "dewpoint_f": 46.0,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 5.6,
                        "gust_kph": 9.0,
                        "uv": 1.0,
                        "air_quality": {
                            "co": 580.7999877929688,
                            "no2": 34.29999923706055,
                            "o3": 4.699999809265137,
                            "so2": 10.0,
                            "pm2_5": 9.699999809265137,
                            "pm10": 24.899999618530273,
                            "us-epa-index": 1,
                            "gb-defra-index": 1
                        }
                    },
                    {
                        "time_epoch": 1688684400,
                        "time": "2023-07-06 20:00",
                        "temp_c": 13.1,
                        "temp_f": 55.6,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 3.1,
                        "wind_kph": 5.0,
                        "wind_degree": 109,
                        "wind_dir": "ESE",
                        "pressure_mb": 1021.0,
                        "pressure_in": 30.15,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 60,
                        "cloud": 4,
                        "feelslike_c": 13.3,
                        "feelslike_f": 55.9,
                        "windchill_c": 13.3,
                        "windchill_f": 55.9,
                        "heatindex_c": 13.1,
                        "heatindex_f": 55.6,
                        "dewpoint_c": 5.6,
                        "dewpoint_f": 42.1,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 6.5,
                        "gust_kph": 10.4,
                        "uv": 1.0,
                        "air_quality": {
                            "co": 587.5,
                            "no2": 32.599998474121094,
                            "o3": 4.599999904632568,
                            "so2": 10.399999618530273,
                            "pm2_5": 10.899999618530273,
                            "pm10": 27.299999237060547,
                            "us-epa-index": 1,
                            "gb-defra-index": 1
                        }
                    },
                    {
                        "time_epoch": 1688688000,
                        "time": "2023-07-06 21:00",
                        "temp_c": 12.5,
                        "temp_f": 54.5,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 3.4,
                        "wind_kph": 5.4,
                        "wind_degree": 107,
                        "wind_dir": "ESE",
                        "pressure_mb": 1021.0,
                        "pressure_in": 30.16,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 64,
                        "cloud": 4,
                        "feelslike_c": 12.5,
                        "feelslike_f": 54.5,
                        "windchill_c": 12.5,
                        "windchill_f": 54.5,
                        "heatindex_c": 12.5,
                        "heatindex_f": 54.5,
                        "dewpoint_c": 5.9,
                        "dewpoint_f": 42.6,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 6.9,
                        "gust_kph": 11.2,
                        "uv": 1.0,
                        "air_quality": {
                            "co": 547.4000244140625,
                            "no2": 27.799999237060547,
                            "o3": 8.100000381469727,
                            "so2": 9.800000190734863,
                            "pm2_5": 10.600000381469727,
                            "pm10": 26.100000381469727,
                            "us-epa-index": 1,
                            "gb-defra-index": 1
                        }
                    },
                    {
                        "time_epoch": 1688691600,
                        "time": "2023-07-06 22:00",
                        "temp_c": 11.9,
                        "temp_f": 53.4,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 3.6,
                        "wind_kph": 5.8,
                        "wind_degree": 102,
                        "wind_dir": "ESE",
                        "pressure_mb": 1021.0,
                        "pressure_in": 30.16,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 67,
                        "cloud": 4,
                        "feelslike_c": 11.7,
                        "feelslike_f": 53.1,
                        "windchill_c": 11.7,
                        "windchill_f": 53.1,
                        "heatindex_c": 11.9,
                        "heatindex_f": 53.4,
                        "dewpoint_c": 6.1,
                        "dewpoint_f": 43.0,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 7.6,
                        "gust_kph": 12.2,
                        "uv": 1.0,
                        "air_quality": {
                            "co": 494.0,
                            "no2": 23.0,
                            "o3": 13.800000190734863,
                            "so2": 8.600000381469727,
                            "pm2_5": 9.0,
                            "pm10": 22.5,
                            "us-epa-index": 1,
                            "gb-defra-index": 1
                        }
                    },
                    {
                        "time_epoch": 1688695200,
                        "time": "2023-07-06 23:00",
                        "temp_c": 11.5,
                        "temp_f": 52.7,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 3.6,
                        "wind_kph": 5.8,
                        "wind_degree": 109,
                        "wind_dir": "ESE",
                        "pressure_mb": 1021.0,
                        "pressure_in": 30.16,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 70,
                        "cloud": 5,
                        "feelslike_c": 11.3,
                        "feelslike_f": 52.3,
                        "windchill_c": 11.3,
                        "windchill_f": 52.3,
                        "heatindex_c": 11.5,
                        "heatindex_f": 52.7,
                        "dewpoint_c": 6.2,
                        "dewpoint_f": 43.2,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 7.6,
                        "gust_kph": 12.2,
                        "uv": 1.0,
                        "air_quality": {
                            "co": 440.6000061035156,
                            "no2": 19.399999618530273,
                            "o3": 18.600000381469727,
                            "so2": 7.300000190734863,
                            "pm2_5": 7.099999904632568,
                            "pm10": 18.899999618530273,
                            "us-epa-index": 1,
                            "gb-defra-index": 1
                        }
                    }
                ]
            }
        ]
    },
    "alerts": {
        "alert": [
            
        ]
    }
}